
name: deploy

on:
  push:
    branches:
      - "master"

jobs:
  hello:
    runs-on: ubuntu-18.04
    steps:
      - name: deployment1
        run: "npm i"
      - name: deployment2
        run: "npm run build"
      - name: deployment3
        run: "npm run start"